name: HOGE

on: push

jobs:
  kr:
    name: kr
    runs-on: ubuntu-20.04
    if: "contains(github.event.head_commit.message, '[run ci]')"
    steps:
      - uses: actions/checkout@v2
      - name: hi
        run: echo Hello, world!

      - name: pwd
        run: pwd

      - name: ls
        run: ls -arl

      - name: gcc version
        run: |
          gcc --version
          g++ --version
      - name: branch
        run: git branch -a | cat

      - name: build
        run: g++ main.cpp -o main

      - name: run
        run: ./main

      - name: ex run
        run: ./main ex

      - name: ls
        run: ls -arl
  unit:
    name: uniunit
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: build
        run: g++ main.cpp -o main

      - name: ex run
        run: ./main ex
  win:
    name: windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: gcc version
        run: |
          gcc --version
          g++ --version
      - name: python version
        run: python --version

      - name: sysi
        run: systeminfo 

      - name: awk v
        run: awk --version

      - name: vv
        run: |
          $hoge="aaaa"
          echo $hoge

      - name: l
        run: ls /

      - name: a
        run: if ( ! -d /tmp ); then mkdir /tmp; fi

      - name: l
        run: ls /



